## 1- Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

# Path for connect to CSV files location
data_path = Path("/Users/tonydawra/Downloads/projectfocstry/datasets")

# Abbreviations for each file according to file names
country_list = ['CA','DE','FR','GB','IN','JP','KR','MX','RU','US']

#  This list for combine each country's DataFrame
all_files = []

# #Loop for reading every CSV file based on country code and add a "country" column
for country in country_list:
    # Reaching each file based on country name
    file_path = data_path / f"{country}videos.csv"
    
    # Read the CSV; ignore errors because of "RUvideos", "JPvideos","USvideos" files
    df_country = pd.read_csv(file_path, encoding='utf-8', encoding_errors="ignore")
    
    # Creating new column for country names in order to concatenate 
    df_country["country"] = country
    
    # Store this temporary DataFrame in the list
    all_files.append(df_country)

# Concatenate all DataFrames by using country column
df = pd.concat(all_files, ignore_index=True)

## 2- Delete no tags

In [2]:
# Keep only rows where the "tags" column is different from the literal string "[none]"
df = df[df["tags"] != "[none]"]
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

## 3. For each channel, determine the total number of views

In [3]:
# Group by channel title and sum the views across all its videos
df.groupby("channel_title")[["views"]].sum()

                 views
channel_title
! 세상에 무슨일이     3942977
!!8時だよ面白ネタ大集合    50207
!t Live         240038
!内ラチの上を走れ        11528
!島ちゃん          1061020
...                ...
５分でできる DIY      272607
ＢＡＳＨｔｖ          116292
Ｋのフィッシングちゃんねる    37165
ＷＡＪＯＩＫＡ         424129
💜Sandrea        347155

[30737 rows x 1 columns]

## 4-Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [4]:
# Select the rows that meet one of these conditions:
#  - comments_disabled == True AND ratings_disabled == True
#  - video_error_or_removed == True
excluded = df[((df["comments_disabled"] == True) & (df["ratings_disabled"] == True)) | (df["video_error_or_removed"] == True)]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
173,H8IWLEtFt9A,17.14.11,Intégrale - On n'est pas couché 11 novembre 20...,On n'est pas couché,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,Intégrale - On n'est pas couché 11 novembre 20...,CA
1069,om-_yJaSW_Y,17.19.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",523258,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1278,om-_yJaSW_Y,17.20.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1004809,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1320,faJOpxEyTWk,17.20.11,Intégrale - On n'est pas couché 18 novembre 20...,On n'est pas couché,24,2017-11-19T02:01:15.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",87544,0,0,0,https://i.ytimg.com/vi/faJOpxEyTWk/default.jpg,True,True,False,Intégrale - On n'est pas couché 18 novembre 20...,CA
1573,om-_yJaSW_Y,17.21.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1197269,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368180,1Aoc-cd9eYs,18.07.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",672609,4916,197,1269,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368407,1Aoc-cd9eYs,18.08.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",412323,25441,208,952,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368613,1Aoc-cd9eYs,18.09.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",251857,6623,231,1120,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368830,1Aoc-cd9eYs,18.10.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",629055,30695,277,1033,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
369587,1Aoc-cd9eYs,18.14.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",1062499,32276,4594,5547,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US

In [5]:
# Now clean the main dataframe by *removing* those rows
df = df[((df["comments_disabled"] != True) & (df["ratings_disabled"] != True)) | (df["video_error_or_removed"] != True)]
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375936,1PhPYr_9zRY,18.14.06,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18T16:39:29.000Z,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,62610,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ...",US
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

## 5- Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [6]:
# Create a new column with the ratio of likes to dislikes
df["like_ratio"] = df["likes"] / df["dislikes"]
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044

In [7]:
# just inspect the three relevant columns
df[["likes", "dislikes", "like_ratio"]].head()

     likes  dislikes  like_ratio
0   787425     43420   18.135076
1   127794      1688   75.707346
2   146035      5339   27.352500
3   132239      1989   66.485168
4  1634130     21082   77.513044

## 6- Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [8]:
# Convert the publish_time column to datetime; any invalid format becomes NaT
df["publish_time"] = pd.to_datetime(df["publish_time"], errors="coerce")

# "Floor" each publish_time to the previous 10-minute mark
df["publish_interval_10m"] = df["publish_time"].dt.floor("10min")

df[["publish_time", "publish_interval_10m"]].head()

               publish_time      publish_interval_10m
0 2017-11-10 17:00:03+00:00 2017-11-10 17:00:00+00:00
1 2017-11-13 17:00:00+00:00 2017-11-13 17:00:00+00:00
2 2017-11-12 19:05:24+00:00 2017-11-12 19:00:00+00:00
3 2017-11-12 18:01:41+00:00 2017-11-12 18:00:00+00:00
4 2017-11-09 11:04:14+00:00 2017-11-09 11:00:00+00:00

## 7- For each interval, determine the number of videos, average number of likes and of dislikes.

In [9]:
# Group by the 10-minute interval
grouped = df.groupby("publish_interval_10m")

# Compute mean likes and dislikes per interval
interval_stats = grouped[["likes", "dislikes"]].mean()

# Add a column with the number of videos in each interval
interval_stats["n_videos"] = grouped.size()

# Reset the index so that publish_interval_10m becomes a normal column
interval_stats = interval_stats.reset_index()
interval_stats

           publish_interval_10m        likes  dislikes  n_videos
0     2006-07-23 08:20:00+00:00   459.000000  152.0000         1
1     2007-03-05 16:20:00+00:00   336.666667    2.0000         9
2     2007-06-25 06:50:00+00:00   579.833333   11.5000        12
3     2007-12-03 20:50:00+00:00   187.937500   15.6875        16
4     2008-01-07 21:20:00+00:00    99.900000    2.0000        10
...                         ...          ...       ...       ...
29859 2018-06-14 02:20:00+00:00  2575.000000  328.0000         1
29860 2018-06-14 02:30:00+00:00   853.000000   77.0000         1
29861 2018-06-14 03:20:00+00:00  1414.000000   28.0000         1
29862 2018-06-14 03:30:00+00:00  8481.000000  252.0000         1
29863 2018-06-14 03:40:00+00:00   374.000000   24.0000         1

[29864 rows x 4 columns]

## 8- For each tag, determine the number of videos
Notice that tags contains a string with several tags.

In [10]:
# Work on a copy to avoid accidentally modifying the original df
df_tags = df.copy()

# Explode the "tags" string into one row per tag:
#  1. Drop rows where "tags" is NaN
#  2. Split the "tags" string on "|" into a list
#  3. explode() creates one row per element of that list
df_tags_exploded = (
    df_tags
    .dropna(subset=["tags"])
    .assign(tag_list=lambda x: x["tags"].str.split("|"))
    .explode("tag_list")
)

# Clean the exploded tag: remove extra spaces and surrounding quotes
df_tags_exploded["tag"] = (
    df_tags_exploded["tag_list"]
    .str.strip()
    .str.strip('"')
)

# We no longer need the intermediate list column
df_tags_exploded = df_tags_exploded.drop(columns=["tag_list"])

# Inspect how tags look now
df_tags_exploded[["video_id", "tags", "tag", "country"]]

,video_id,tags,tag,country
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Eminem,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Walk,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",On,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Water,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Aftermath/Shady/Interscope,CA
...,...,...,...,...
375940,oV0zkMe1K8s,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",ending explained,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",call of duty,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",cod,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",activision,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",Black Ops 4,US

In [11]:
# Count how many *distinct* videos contain each tag
videos_per_tag = (
    df_tags_exploded.groupby("tag")["video_id"]
    .nunique()                     # number of distinct videos per tag
    .reset_index(name="n_videos")
)

## 9- Find the tags with the largest number of videos

In [12]:
# Sort tags by number of videos (descending) and look at the top 10
top_tags = videos_per_tag.sort_values("n_videos", ascending=False)
top_tags.head(10)

               tag  n_videos
11759         2018      5771
356784       funny      4150
296931      comedy      3107
467930        news      3079
11403         2017      2661
587774       video      2084
536803        show      2052
578086          tv      1732
561569  television      1721
696595     новости      1553

## 10- For each (tag, country) pair, compute average ratio likes/dislikes

In [13]:
# Aggregate total likes, total dislikes, and number of rows (videos) per (tag, country)
df_sum_like_ratio = df_tags_exploded.groupby(["tag", "country"]).agg(
    {
        "likes": "sum",
        "dislikes": "sum",
        "video_id": "count"
    }
)

# Compute the like/dislike ratio using the aggregated sums
df_sum_like_ratio["like_ratio_tag_country"] = (
    df_sum_like_ratio["likes"] / df_sum_like_ratio["dislikes"]
)

# Replace infinite values (division by zero) with 0 and fill NaN with 0
df_sum_like_ratio["like_ratio_tag_country"] = (
    df_sum_like_ratio["like_ratio_tag_country"]
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

df_sum_like_ratio

                                                           likes  dislikes  \
tag                                             country
                                                CA        308155     33694
                                                DE        123197     11794
                                                FR        122908     12332
                                                IN       1868645    285522
                                                JP        120798     12223
...                                                          ...       ...
😥                                               DE           396        16
😭 #résistancelamaindesqueezie ❤️                FR          1073       105
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية FR         12566      2019
🚀 smartpixel.com.ua                             RU             5         7
🤝 ZARBEX zahlt Schutzgeld!!!                    DE          1357        97

                                                         video_id  \
tag                                             country
                                                CA             14
                                                DE             14
                                                FR             14
                                                IN            643
                                                JP              5
...                                                           ...
😥                                               DE              2
😭 #résistancelamaindesqueezie ❤️                FR              1
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية FR              1
🚀 smartpixel.com.ua                             RU              1
🤝 ZARBEX zahlt Schutzgeld!!!                    DE              1

                                                         like_ratio_tag_country
tag                                             country
                                                CA                     9.145694
                                                DE                    10.445735
                                                FR                     9.966591
                                                IN                     6.544662
                                                JP                     9.882844
...                                                                         ...
😥                                               DE                    24.750000
😭 #résistancelamaindesqueezie ❤️                FR                    10.219048
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية FR                     6.223873
🚀 smartpixel.com.ua                             RU                     0.714286
🤝 ZARBEX zahlt Schutzgeld!!!                    DE                    13.989691

[1102613 rows x 4 columns]

## 11- For each (trending_date, country) pair, the video with the largest number of views

In [14]:
# Sum views for each (trending_date, country) pair
top_trending_videos = df.groupby(["trending_date", "country"])["views"].sum()

# Turn the groupby result back into a DataFrame
top_trending_videos = top_trending_videos.reset_index()

# Sort by total views in descending order
top_trending_videos = top_trending_videos.sort_values("views", ascending=False)

top_trending_videos

     trending_date country       views
1098      18.13.05      GB  2078169921
1363      18.18.05      GB  2076604508
1049      18.12.05      GB  2071716332
1588      18.23.03      GB  2069347589
1755      18.26.05      GB  2032459897
...            ...     ...         ...
1913      18.30.03      JP    16345059
814       18.07.04      JP    15320005
1188      18.15.02      JP    13967248
1247      18.16.03      JP    13843390
1198      18.15.03      JP     6579333

[1967 rows x 3 columns]

## 12- Divide trending_date into three columns: year, month, day

In [15]:
# Convert trending_date (string) into a proper datetime;
df["trending_datetime"] = pd.to_datetime(
    df["trending_date"],
    format="%y.%d.%m",   # year.day.month
    errors="coerce"
)

# Extract year, month and day into separate columns
df["trend_year"] = df["trending_datetime"].dt.year
df["trend_month"] = df["trending_datetime"].dt.month
df["trend_day"] = df["trending_datetime"].dt.day


df[["video_id", "trending_date", "trend_year", "trend_month", "trend_day"]]

           video_id trending_date  trend_year  trend_month  trend_day
0       n1WpP7iowLc      17.14.11        2017           11         14
1       0dBIkQ4Mz1M      17.14.11        2017           11         14
2       5qpjK5DgCt4      17.14.11        2017           11         14
3       d380meD0W0M      17.14.11        2017           11         14
4       2Vv-BfVoq4g      17.14.11        2017           11         14
...             ...           ...         ...          ...        ...
375936  1PhPYr_9zRY      18.14.06        2018            6         14
375937  BZt0qjTWNhw      18.14.06        2018            6         14
375939  D6Oy4LfoqsU      18.14.06        2018            6         14
375940  oV0zkMe1K8s      18.14.06        2018            6         14
375941  ooyjaVdt-jA      18.14.06        2018            6         14

[338244 rows x 5 columns]

## 13- For each (month, country) pair, the video with the largest number of views

In [16]:
# Aggregate total views per (trend_month, country, video_id)
top_trending_videos_month = df.groupby(
    ["trend_month", "country", "video_id"]
)["views"].sum()

# Convert groupby result to a DataFrame
top_trending_videos_month = top_trending_videos_month.reset_index()

# Sort by views to see the videos with most views per month/country
top_trending_videos_month = top_trending_videos_month.sort_values(
    "views", ascending=False
)

top_trending_videos_month

        trend_month country     video_id       views
63882             3      GB  kLpH1nSLJSs  5897068430
63780             3      GB  _I_D_8Z4sJE  5482858729
63977             3      GB  xpVfcZ0ZcFM  4232881214
36724             2      GB  wfWkmURBNv8  4107192909
115666            5      GB  9jI-z9QN6g8  3838465705
...             ...     ...          ...         ...
124062            5      MX  IFUVQf_x3vU         255
49869             2      RU  p3YzdrKZzAw         164
46894             2      RU  8_xuskv0SVw         163
155159           11      MX  AH9CPLoIWu4         157
49575             2      RU  kz9Q2oALmWE         153

[187717 rows x 4 columns]

## 14- Read all json files with the video categories

In [17]:
import json

# Re-use the same data_path and country_list defined above

all_categories = []

for country in country_list:
    # e.g. "US_category_id.json"
    jf = data_path / f"{country}_category_id.json"
    
    # Read file content as text 
    raw_text = jf.read_text(encoding="utf-8")
    
    # Parse JSON into a Python dictionary
    data = json.loads(raw_text)
    
    # Extract the "items" list that contains category metadata
    items = data.get("items", [])
    
    # Flatten nested JSON into a DataFrame
    cat_df = pd.json_normalize(items)
    
    # Keep only ID, title, and assignable flag, and rename columns
    cat_df = cat_df[["id", "snippet.title", "snippet.assignable"]].rename(
        columns={
            "id": "category_id",
            "snippet.title": "category_name",
            "snippet.assignable": "assignable"
        }
    )

    # Make sure category_id is a string and add the country column
    cat_df["category_id"] = cat_df["category_id"].astype(str)
    cat_df["country"] = country   

    # Store this intermediate DataFrame
    all_categories.append(cat_df)

# One big DataFrame with all categories and all countries
categories_df = pd.concat(all_categories, ignore_index=True)

categories_df.head(30)

   category_id         category_name  assignable country
0            1      Film & Animation        True      CA
1            2      Autos & Vehicles        True      CA
2           10                 Music        True      CA
3           15        Pets & Animals        True      CA
4           17                Sports        True      CA
5           18          Short Movies       False      CA
6           19       Travel & Events        True      CA
7           20                Gaming        True      CA
8           21         Videoblogging       False      CA
9           22        People & Blogs        True      CA
10          23                Comedy        True      CA
11          24         Entertainment        True      CA
12          25       News & Politics        True      CA
13          26         Howto & Style        True      CA
14          27             Education        True      CA
15          28  Science & Technology        True      CA
16          30                Movies       False      CA
17          31       Anime/Animation       False      CA
18          32      Action/Adventure       False      CA
19          33              Classics       False      CA
20          34                Comedy       False      CA
21          35           Documentary       False      CA
22          36                 Drama       False      CA
23          37                Family       False      CA
24          38               Foreign       False      CA
25          39                Horror       False      CA
26          40        Sci-Fi/Fantasy       False      CA
27          41              Thriller       False      CA
28          42                Shorts       False      CA
29          43                 Shows       False      CA

## 15. For each country, determine how many videos have a category that is not assignable.

In [20]:
# Filter categories that are NOT assignable
categories_nassignable = categories_df[categories_df["assignable"] == False]

# Ensure the join keys have the same type (string) in both dataframes
categories_nassignable["category_id"] = categories_nassignable["category_id"].astype(str)
df["category_id"] = df["category_id"].astype(str)

# Inner join: keep only rows whose (category_id, country) exist in both tables
df_merge = categories_nassignable.merge(
    df,
    on=["category_id", "country"],
    how="inner"
)

# Group by country and non-assignable category_id and count how many videos
assignable_video = df_merge.groupby(["country", "category_id"])[["video_id"]].count()
assignable_video=assignable_video.reset_index()
assignable_video

/var/folders/mp/yz1h5zm55vggj3tcjjgkpv_80000gn/T/ipykernel_6470/3274523877.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  categories_nassignable["category_id"] = categories_nassignable["category_id"].astype(str)

   country category_id  video_id
0       CA          30         6
1       CA          43       123
2       DE          30         2
3       DE          43       106
4       FR          30        11
5       FR          43        99
6       GB          43        20
7       IN          30        16
8       IN          43       205
9       KR          43       165
10      MX          43         3
11      RU          30         1
12      RU          43       194
13      US          43        57