## 1- Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

# Path where all the country CSV files are stored
data_path = Path("/Users/tonydawra/Downloads/projectfocstry/datasets")

# List of country codes used in the file names (e.g. "USvideos.csv")
country_list = ['CA','DE','FR','GB','IN','JP','KR','MX','RU','US']

# This list will temporarily store each country's DataFrame
all_files = []

# Loop over every country code, read its CSV and add a "country" column
for country in country_list:
    # Build the full CSV path for the current country
    file_path = data_path / f"{country}videos.csv"
    
    # Read the CSV; ignore errors in the encoding if any character is problematic
    df_country = pd.read_csv(file_path, encoding='utf-8', encoding_errors="ignore")
    
    # Add the ISO country code so that later we know where each row comes from
    df_country["country"] = country
    
    # Store this temporary DataFrame in the list
    all_files.append(df_country)

# Concatenate all country DataFrames into a single big DataFrame
df = pd.concat(all_files, ignore_index=True)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,GB
375938,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,GB
375939,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,GB
375940,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,GB
375941,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,GB

## 2- Delete no tags

In [ ]:
# Keep only rows where the "tags" column is different from the literal string "[none]"
df = df[df["tags"] != "[none]"]
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX

## 3. For each channel, determine the total number of views

In [ ]:
# Group by channel title and sum the views across all its videos
df.groupby("channel_title")[["views"]].sum()

channel_title
! 세상에 무슨일이       3942977
!!8時だよ面白ネタ大集合      50207
!t Live           240038
!内ラチの上を走れ          11528
!島ちゃん            1061020
                  ...
５分でできる DIY        272607
ＢＡＳＨｔｖ            116292
Ｋのフィッシングちゃんねる      37165
ＷＡＪＯＩＫＡ           424129
💜Sandrea          347155
Name: views, Length: 30737, dtype: int64

## 4-Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [18]:
excluded = df[((df["comments_disabled"] == True) & (df["ratings_disabled"] == True)) | (df["video_error_or_removed"] == True)]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
14,Dhhp8M5K3UI,17.14.11,Deleted video,Harrison,24,2017-11-13T04:44:51.000Z,"terremoto costa rica|""Primeras imagenes sismo ...",53265,194,41,90,https://i.ytimg.com/vi/7jmJtdqI6YE/default.jpg,False,False,True,Un sismo de magnitud 6.5 sacudió el domingo po...,MX
88,qxyJYWGf57k,17.14.11,Santa Misa del lunes 13 de noviembre de 2017 (...,Maria de Nazaret,27,2017-11-13T10:31:51.000Z,"Santa misa de hoy|""Santa Misa""|""Misa del dia d...",8010,0,0,0,https://i.ytimg.com/vi/qxyJYWGf57k/default.jpg,True,True,False,→ Suscríbete aquí y sigue la Misa diaria en es...,MX
2505,BvXaDlbse3o,17.26.11,Eclesiastés/Cohelet Capítulo 7 Parte 2 por el ...,Shalom132,22,2017-11-26T00:44:37.000Z,"Torah|""Proteccion divina""|""Mesianicos""|""Mesian...",3356,0,0,0,https://i.ytimg.com/vi/BvXaDlbse3o/default.jpg,True,True,False,"El Libro de Cohelet, también conocido como Ecl...",MX
2540,KJLhe5oRUkA,17.26.11,Sobrevuelo al Popocatépetl 25 de noviembre 2017,Secretaría de Gobernación,25,2017-11-25T22:31:16.000Z,"Secretaría de Gobernación|""Gobierno de la Repú...",20692,0,0,0,https://i.ytimg.com/vi/KJLhe5oRUkA/default.jpg,True,True,False,El CENAPRED realiza el monitoreo del volcán en...,MX
4272,W9Y3KYKtR0g,17.05.12,JW BROADCASTING DICIEMBRE 2017. ESPAÑOL,DISCURSOS T.J.,22,2017-12-04T16:36:50.000Z,jw broadcasting diciembre 2017 español,16468,0,0,0,https://i.ytimg.com/vi/W9Y3KYKtR0g/default.jpg,True,True,False,JW BROADCASTING DICIEMBRE 2017. ESPANOL.,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375240,QW8whgmyTNU,18.10.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3125979,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375408,QW8whgmyTNU,18.11.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3130833,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375581,QW8whgmyTNU,18.12.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3140732,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375756,QW8whgmyTNU,18.13.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3149925,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375926,QW8whgmyTNU,18.14.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3158685,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB

In [19]:
df = df[((df["comments_disabled"] != True) & (df["ratings_disabled"] != True)) | (df["video_error_or_removed"] != True)]
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,GB
375938,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,GB
375939,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,GB
375940,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,GB
375941,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,GB

## 5- Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [ ]:
# Create a new column with the ratio of likes to dislikes
df["like_ratio"] = df["likes"] / df["dislikes"]
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_time_round,publish_interval_10m
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13 06:06:22+00:00,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX,11.584488,2017-11-13 06:10:00+00:00,2017-11-13 06:10:00+00:00
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13 05:11:58+00:00,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX,1.557471,2017-11-13 05:10:00+00:00,2017-11-13 05:10:00+00:00
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13 17:00:02+00:00,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX,37.988722,2017-11-13 17:00:00+00:00,2017-11-13 17:00:00+00:00
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13 03:47:10+00:00,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX,2.210526,2017-11-13 03:50:00+00:00,2017-11-13 03:50:00+00:00
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13 19:17:48+00:00,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX,84.847283,2017-11-13 19:20:00+00:00,2017-11-13 19:20:00+00:00

In [27]:
df[["likes", "dislikes", "like_ratio"]].head()

   likes  dislikes  like_ratio
0   4182       361   11.584488
1    271       174    1.557471
2  10105       266   37.988722
3    378       171    2.210526
4  57781       681   84.847283

## 6- Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [24]:
df["publish_time"] = pd.to_datetime(df["publish_time"], errors= "coerce")
df["publish_interval_10m"] = df["publish_time"].dt.round("10min")
df[["publish_time", "publish_interval_10m"]].head()

               publish_time      publish_interval_10m
0 2017-11-13 06:06:22+00:00 2017-11-13 06:10:00+00:00
1 2017-11-13 05:11:58+00:00 2017-11-13 05:10:00+00:00
2 2017-11-13 17:00:02+00:00 2017-11-13 17:00:00+00:00
3 2017-11-13 03:47:10+00:00 2017-11-13 03:50:00+00:00
4 2017-11-13 19:17:48+00:00 2017-11-13 19:20:00+00:00

## 7- For each interval, determine the number of videos, average number of likes and of dislikes.

In [25]:
grouped = df.groupby("publish_interval_10m")

interval_stats = grouped[[ "likes", "dislikes"]].mean()
interval_stats["n_videos"] = grouped.size()
interval_stats = interval_stats.reset_index()
interval_stats

           publish_interval_10m         likes   dislikes  n_videos
0     2006-07-23 08:20:00+00:00    459.000000   152.0000         1
1     2007-03-05 16:20:00+00:00    336.666667     2.0000         9
2     2007-06-25 06:50:00+00:00    579.833333    11.5000        12
3     2007-12-03 20:50:00+00:00    187.937500    15.6875        16
4     2008-01-07 21:20:00+00:00     99.900000     2.0000        10
...                         ...           ...        ...       ...
29898 2018-06-14 01:50:00+00:00  26276.000000   426.5000         2
29899 2018-06-14 02:20:00+00:00  58092.000000  3325.0000         1
29900 2018-06-14 02:30:00+00:00   1714.000000   202.5000         2
29901 2018-06-14 03:30:00+00:00   4947.500000   140.0000         2
29902 2018-06-14 03:40:00+00:00    374.000000    24.0000         1

[29903 rows x 4 columns]